### ISSUE TITLE
2022 data

### ISSUE THREAD

**Issue by Airpino** [ikashnitsky/sjrdata#2]
Are you planning to integrate 2022 data?

**Comment by faisalmustafa** [comment]
Will be it possible to combine the 2022 data into the current data?

**Comment by Renzo856** [comment]
Hello. Could you add the 2022 data?

**Comment by cannin** [comment]
For anyone that simply wants journal data from 2022, you can download the data from https://www.scimagojr.com/journalrank.php?year=2022&out=xls and load the file. Note: I think 2022 adds the "Areas" column. 

```
# Download Source: https://www.scimagojr.com/journalrank.php
sjr_year <- "2022"
sjr_journals <- read.csv(paste0("scimagojr ", sjr_year, ".csv"), sep=";", stringsAsFactors=FALSE)
sjr_journals <- cbind(year=sjr_year, sjr_journals)
colnames(sjr_journals) <- c("year", "rank", "sourceid", "title", "type", "issn", "sjr", 
                            "sjr_best_quartile", "h_index", "total_docs_year", "total_docs_3years", 
                            "total_refs", "total_cites_3years", "citable_docs_3years", "cites_doc_2years", 
                            "ref_doc", "country", "region", "publisher", "coverage", "categories", "areas")
```

Data downloading described here: https://github.com/ikashnitsky/sjrdata/blob/master/dev/sjr-get-data-download-read-incremental.R#L29-L42

**Comment by ikashnitsky** [comment]
Fixed recently. Apologies for the delay
